/**
 * @fileoverview Core type definitions and constants for the IPN P2P Payment system.
 *
 * This module defines the data contracts between client and server, matching
 * the IPN Mock API Specification exactly. All types use strict typing to
 * prevent common payment system bugs (e.g., account numbers as strings to
 * preserve leading zeros).
 *
 * @see IPN Developer Integration Challenge — Mock API Specification (pages 3–5)
 */

// ---------------------------------------------------------------------------
// Payment Status
// ---------------------------------------------------------------------------

/**
 * Possible outcomes of a P2P payment transaction.
 * Matches the IPN API spec Section 7 — Response Structure.
 */
export type PaymentStatus = "SUCCESS" | "FAILED";

// ---------------------------------------------------------------------------
// Error Codes
// ---------------------------------------------------------------------------

/**
 * IPN error code definitions mapping each code to its HTTP status and
 * human-readable description.
 *
 * @see IPN Mock API Specification — Section 9 (Error Responses)
 *
 * @example
 * ```ts
 * const err = ERROR_CODES.ERR001;
 * console.log(err.httpStatus); // 400
 * console.log(err.description); // "Missing required field"
 * ```
 */
export const ERROR_CODES = {
  ERR001: { httpStatus: 400, description: "Missing required field" },
  ERR002: { httpStatus: 400, description: "Invalid account number format" },
  ERR003: { httpStatus: 400, description: "Invalid currency" },
  ERR004: { httpStatus: 400, description: "Invalid amount" },
  ERR005: { httpStatus: 402, description: "Insufficient funds" },
  ERR006: { httpStatus: 500, description: "Internal processing error" },
} as const;

/**
 * Union type of all valid IPN error codes (ERR001–ERR006).
 * Derived from the ERROR_CODES constant to ensure they stay in sync.
 */
export type ErrorCode = keyof typeof ERROR_CODES;

// ---------------------------------------------------------------------------
// Request
// ---------------------------------------------------------------------------

/**
 * Shape of a P2P payment request sent to `POST /api/p2p-payment`.
 *
 * **Important design notes:**
 * - `senderAccountNumber` and `receiverAccountNumber` are `string`, not `number`.
 *   Real bank account numbers can have leading zeros (e.g., `"0987654321"`).
 *   Storing them as numbers would silently drop those zeros and corrupt the data.
 * - `amount` is `number` but must be > 0. Floating-point precision is handled
 *   by rounding to 2 decimal places during validation.
 * - `currency` must be `"NAD"` (Namibian Dollar, ISO 4217).
 *
 * @see IPN Mock API Specification — Section 4 (Request Fields)
 */
export interface P2PPaymentRequest {
  /** Unique transaction reference generated by the client. Format: REF-YYYYMMDD-XXXXX */
  clientReference: string;
  /** Sender's bank account number. Numeric characters only, minimum 10 digits. */
  senderAccountNumber: string;
  /** Receiver's bank account number. Numeric characters only, minimum 10 digits. */
  receiverAccountNumber: string;
  /** Payment amount in the specified currency. Must be greater than 0. */
  amount: number;
  /** ISO 4217 currency code. Must be "NAD" (Namibian Dollar). */
  currency: string;
  /** User-entered payment reference/description. Max 50 characters. */
  reference: string;
}

// ---------------------------------------------------------------------------
// Response
// ---------------------------------------------------------------------------

/**
 * Shape of the API response from `POST /api/p2p-payment`.
 *
 * On success: `status` is `"SUCCESS"`, `transactionId` is populated, `errorCode` is `null`.
 * On failure: `status` is `"FAILED"`, `errorCode` contains the specific error, `transactionId` is `null`.
 *
 * @see IPN Mock API Specification — Sections 7–10
 *
 * @example
 * ```ts
 * // Success response
 * const success: P2PPaymentResponse = {
 *   status: "SUCCESS",
 *   errorCode: null,
 *   transactionId: "TXN20260315143022-0001",
 *   message: "Payment processed successfully",
 * };
 *
 * // Failure response
 * const failure: P2PPaymentResponse = {
 *   status: "FAILED",
 *   errorCode: "ERR005",
 *   transactionId: null,
 *   message: "Insufficient funds",
 * };
 * ```
 */
export interface P2PPaymentResponse {
  /** Transaction outcome — "SUCCESS" or "FAILED". */
  status: PaymentStatus;
  /** IPN error code if the transaction failed, otherwise null. */
  errorCode: ErrorCode | null;
  /** Server-generated transaction identifier on success, otherwise null. */
  transactionId: string | null;
  /** Human-readable description of the transaction outcome. */
  message: string;
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/**
 * Maximum payment amount before the mock API simulates an "Insufficient funds"
 * error (ERR005).
 *
 * **Why 10,000 NAD**: The spec doesn't define when ERR005 triggers. In a real
 * system this would check account balances. We simulate with a threshold because:
 * - It's deterministic and easy for reviewers to test
 * - It's realistic — many payment systems enforce per-transaction limits
 * - It avoids random behavior that would make testing unreliable
 *
 * @see ASSUMPTIONS.md — Section "Error Simulation"
 */
export const INSUFFICIENT_FUNDS_THRESHOLD = 10_000;

/**
 * Suffix that, when present at the end of a `clientReference`, forces
 * the mock API to return ERR006 (Internal processing error).
 * This provides a deterministic way to test error handling.
 *
 * @example
 * ```ts
 * // This request will always return ERR006
 * const request = { clientReference: "REF-20260315-abc12-ERR", ... };
 * ```
 */
export const FORCE_ERROR_SUFFIX = "-ERR";
