/**
 * @fileoverview Zod validation schemas for P2P payment requests.
 *
 * These schemas are shared between client (form validation) and server
 * (API endpoint validation). This "defense in depth" approach ensures:
 * - Client-side: instant feedback for the user (UX)
 * - Server-side: security — never trust data from the client
 * - Both sides use the SAME rules, so they can't drift apart
 *
 * This mirrors how real payment APIs work: validate at every boundary.
 *
 * @see IPN Mock API Specification — Section 5 (Validation Rules)
 */

import { z } from "zod/v4";

// ---------------------------------------------------------------------------
// Individual Field Schemas
// ---------------------------------------------------------------------------

/**
 * Validates a bank account number per IPN spec rules:
 * - Must be a string (preserves leading zeros like "0987654321")
 * - Must contain only digit characters (0–9)
 * - Must be at least 10 characters long
 *
 * @param fieldName - Human-readable field name for error messages
 * @returns A Zod string schema with account number validation
 *
 * @example
 * ```ts
 * const schema = accountNumberSchema("Sender account number");
 * schema.parse("1234567890");   // OK
 * schema.parse("12345");        // Error: "at least 10 digits"
 * schema.parse("12345ABCDE");   // Error: "numeric characters only"
 * ```
 */
function accountNumberSchema(fieldName: string) {
  return z
    .string()
    .min(10, `${fieldName} must be at least 10 digits`)
    .regex(/^\d+$/, `${fieldName} must contain numeric characters only`);
}

// ---------------------------------------------------------------------------
// Payment Request Schema
// ---------------------------------------------------------------------------

/**
 * Complete Zod schema for validating a P2P payment request.
 *
 * Validates all 6 required fields per the IPN Mock API Specification:
 * - `clientReference`: non-empty string (auto-generated by the client)
 * - `senderAccountNumber`: numeric string, min 10 digits
 * - `receiverAccountNumber`: numeric string, min 10 digits, must differ from sender
 * - `amount`: positive number, rounded to 2 decimal places
 * - `currency`: must be exactly "NAD"
 * - `reference`: 1–50 characters
 *
 * **Design note on `amount`**: JavaScript uses IEEE 754 floating point,
 * where `0.1 + 0.2 !== 0.3`. We round to 2 decimal places to handle
 * this. Real payment systems use integer cents or Decimal libraries.
 *
 * @example
 * ```ts
 * const result = paymentRequestSchema.safeParse({
 *   clientReference: "REF-20260315-a3f2b",
 *   senderAccountNumber: "1234567890",
 *   receiverAccountNumber: "0987654321",
 *   amount: 150.00,
 *   currency: "NAD",
 *   reference: "Lunch payment",
 * });
 *
 * if (result.success) {
 *   console.log(result.data); // Validated & transformed data
 * } else {
 *   console.log(result.error.issues); // Validation errors
 * }
 * ```
 */
export const paymentRequestSchema = z
  .object({
    clientReference: z
      .string()
      .min(1, "Client reference is required"),

    senderAccountNumber: accountNumberSchema("Sender account number"),

    receiverAccountNumber: accountNumberSchema("Receiver account number"),

    amount: z
      .number({ message: "Amount is required and must be a valid number" })
      .positive("Amount must be greater than 0")
      .transform((val) => Math.round(val * 100) / 100),

    currency: z
      .string()
      .refine((val) => val === "NAD", {
        message: "Currency must be NAD (Namibian Dollar)",
      }),

    reference: z
      .string()
      .min(1, "Payment reference is required")
      .max(50, "Payment reference must be 50 characters or fewer"),
  })
  .refine(
    (data) => data.senderAccountNumber !== data.receiverAccountNumber,
    {
      message: "Sender and receiver account numbers must be different",
      path: ["receiverAccountNumber"],
    }
  );

/**
 * TypeScript type inferred from the payment request schema.
 * Use this when you need the validated/transformed shape of the data
 * (e.g., amount is already rounded to 2 decimal places).
 */
export type ValidatedPaymentRequest = z.infer<typeof paymentRequestSchema>;

// ---------------------------------------------------------------------------
// Error Code Mapping
// ---------------------------------------------------------------------------

/**
 * Maps Zod validation error paths to IPN error codes.
 *
 * When the server validates a request and finds errors, we need to return
 * the correct IPN error code (ERR001–ERR004) rather than raw Zod messages.
 * This function inspects which field failed and returns the appropriate code.
 *
 * @param issues - Array of Zod validation issues from a failed parse
 * @returns The most appropriate IPN error code for the first validation failure
 *
 * @example
 * ```ts
 * const result = paymentRequestSchema.safeParse(badData);
 * if (!result.success) {
 *   const errorCode = mapZodErrorToIpnCode(result.error.issues);
 *   // => "ERR002" if account number was invalid
 * }
 * ```
 */
export function mapZodErrorToIpnCode(
  issues: z.core.$ZodIssue[]
): "ERR001" | "ERR002" | "ERR003" | "ERR004" {
  const firstIssue = issues[0];
  if (!firstIssue) return "ERR001";

  const path = firstIssue.path?.[0];

  // Currency validation failure → ERR003
  if (path === "currency") return "ERR003";

  // Amount validation failure → ERR004
  if (path === "amount") return "ERR004";

  // Account number validation failure → ERR002
  if (path === "senderAccountNumber" || path === "receiverAccountNumber") {
    // Check if it's a "missing" error vs a "format" error
    const message = firstIssue.message?.toLowerCase() ?? "";
    if (message.includes("required") || message.includes("expected")) {
      return "ERR001";
    }
    return "ERR002";
  }

  // Everything else (missing fields, empty strings) → ERR001
  return "ERR001";
}
