/**
 * @fileoverview Generators for unique transaction identifiers.
 *
 * Two types of IDs exist in the IPN P2P payment flow:
 * - **Client Reference** (`clientReference`): Generated by the client before
 *   submitting. Acts as an idempotency key — if a request times out and the
 *   client retries, the server can detect the duplicate by this reference.
 * - **Transaction ID** (`transactionId`): Generated by the server after
 *   successful processing. This is the server's internal tracking number.
 *
 * This dual-ID pattern is standard in payment systems (SWIFT, Visa Direct, etc.).
 */

// ---------------------------------------------------------------------------
// Client Reference
// ---------------------------------------------------------------------------

/**
 * Generates a unique client reference for tracking a P2P payment transaction.
 *
 * Format: `REF-YYYYMMDD-XXXXX`
 * - `REF` prefix identifies it as a client reference
 * - `YYYYMMDD` is the current date
 * - `XXXXX` is 5 random hex characters for uniqueness
 *
 * The format mirrors the sample in the IPN spec (`REF-20260306-001`) but uses
 * random hex instead of a sequential counter for stateless uniqueness — no
 * database needed to track the next number.
 *
 * @returns A unique client reference string
 *
 * @example
 * ```ts
 * const ref = generateClientReference();
 * // => "REF-20260315-a3f2b"
 * ```
 */
export function generateClientReference(): string {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, "0");
  const day = String(now.getDate()).padStart(2, "0");
  const datePart = `${year}${month}${day}`;

  // 5 random hex characters = 1,048,576 possible values per day
  const randomPart = Math.random().toString(16).slice(2, 7).padEnd(5, "0");

  return `REF-${datePart}-${randomPart}`;
}

// ---------------------------------------------------------------------------
// Transaction ID (Server-Side)
// ---------------------------------------------------------------------------

/** Counter to ensure uniqueness within the same millisecond */
let transactionCounter = 0;

/**
 * Generates a unique server-side transaction ID after successful payment processing.
 *
 * Format: `TXN-YYYYMMDDHHMMSS-NNNN`
 * - `TXN` prefix identifies it as a server transaction
 * - `YYYYMMDDHHMMSS` is the current timestamp
 * - `NNNN` is a 4-digit incrementing counter (wraps at 9999)
 *
 * The counter ensures uniqueness even if two transactions are processed
 * within the same second. In a production system with multiple server
 * instances, you'd use a distributed ID generator (Snowflake, ULID, etc.).
 *
 * @returns A unique transaction ID string
 *
 * @example
 * ```ts
 * const txnId = generateTransactionId();
 * // => "TXN-20260315143022-0001"
 * ```
 */
export function generateTransactionId(): string {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, "0");
  const day = String(now.getDate()).padStart(2, "0");
  const hours = String(now.getHours()).padStart(2, "0");
  const minutes = String(now.getMinutes()).padStart(2, "0");
  const seconds = String(now.getSeconds()).padStart(2, "0");
  const timestamp = `${year}${month}${day}${hours}${minutes}${seconds}`;

  transactionCounter = (transactionCounter + 1) % 10000;
  const counter = String(transactionCounter).padStart(4, "0");

  return `TXN-${timestamp}-${counter}`;
}
